default: &default
  adapter: postgresql
  encoding: unicode
  database: budgetapp_db
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 12345
  host: localhost

development:
  <<: *default
  database: budget_app_development

test:
  <<: *default
  database: budget_app_test

production:
  <<: *default
  database: budget_app_production
