# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  encoding: unicode
  database: budgetapp_db
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 12345
  host: localhost

development:
  <<: *default
  database: budget_app_development

test:
  <<: *default
  database: budget_app_test

production:
  <<: *default
  # database: budget_app_production
  url: <%= ENV['DATABASE_URL'] %>

